[context.production.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "137"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x4509C2B9884988E4452AdaD792ffC2Ff34e882B2"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x4d9869ffda1c5279552c5f3f4d29b899276571a4"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

[build.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "137"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x4509C2B9884988E4452AdaD792ffC2Ff34e882B2"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x4d9869ffda1c5279552c5f3f4d29b899276571a4"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

[context.deploy-preview.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "137"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x4509C2B9884988E4452AdaD792ffC2Ff34e882B2"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x4d9869ffda1c5279552c5f3f4d29b899276571a4"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

