[context.production.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "4"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x3C5f6B3Ea031FBD7A762c0b9df2C63fC263FAa29"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x316AC5cF04bB555DA44C8b8f86deC05B56bBd718"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

[build.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "4"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x3C5f6B3Ea031FBD7A762c0b9df2C63fC263FAa29"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x316AC5cF04bB555DA44C8b8f86deC05B56bBd718"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

[context.deploy-preview.environment]
    NEXT_PUBLIC_HOSTNAME = "/"
    NEXT_PUBLIC_NETWORK_ID = "4"
    NEXT_PUBLIC_PILLAR_DAO_CONTRACT_ADDRESS = "0x3C5f6B3Ea031FBD7A762c0b9df2C63fC263FAa29"
    NEXT_PUBLIC_PILLAR_MEMBERSHIP_CONTRACT_ADDRESS = "0x316AC5cF04bB555DA44C8b8f86deC05B56bBd718"
    NEXT_PUBLIC_OPENSEA_COLLECTION_SLUG = "pillar-dao-membership"

